"""add fencingtracker_id to fencers

Revision ID: 2ba564e47b5d
Revises: fea59cc0d5fd
Create Date: 2025-10-02 14:32:42.274657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba564e47b5d'
down_revision: Union[str, Sequence[str], None] = 'fea59cc0d5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fencers', sa.Column('fencingtracker_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_fencers_fencingtracker_id'), 'fencers', ['fencingtracker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fencers_fencingtracker_id'), table_name='fencers')
    op.drop_column('fencers', 'fencingtracker_id')
    # ### end Alembic commands ###
