"""add tracked_fencers table

Revision ID: fea59cc0d5fd
Revises: 56a663464049
Create Date: 2025-10-02 13:45:24.345707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea59cc0d5fd'
down_revision: Union[str, Sequence[str], None] = '56a663464049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_fencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fencer_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('weapon_filter', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fencer_id', name='uq_tracked_fencers_user_fencer')
    )
    op.create_index(op.f('ix_tracked_fencers_fencer_id'), 'tracked_fencers', ['fencer_id'], unique=False)
    op.create_index(op.f('ix_tracked_fencers_id'), 'tracked_fencers', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_fencers_user_id'), 'tracked_fencers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_fencers_user_id'), table_name='tracked_fencers')
    op.drop_index(op.f('ix_tracked_fencers_id'), table_name='tracked_fencers')
    op.drop_index(op.f('ix_tracked_fencers_fencer_id'), table_name='tracked_fencers')
    op.drop_table('tracked_fencers')
    # ### end Alembic commands ###
